# Generated by Django 4.0.4 on 2022-05-30 19:32

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Team',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120)),
                ('logo', models.CharField(max_length=500)),
                ('red_card', models.IntegerField(default=0)),
                ('yellow_card', models.IntegerField(default=0)),
                ('shots_on_target', models.FloatField(default=0)),
                ('shots', models.FloatField(default=0)),
                ('fouls_committed', models.FloatField(default=0)),
            ],
        ),
    ]
